title = "John Rodewald"
base_url = "https://blog.john-rodewald.github.io"
compile_sass = true
build_search_index = false
theme = "lightspeed"

[markdown]
highlight_code = true

[extra]
footer_links = [
    {url = "$BASE_URL/about", name = "About"},
    {url = "https://www.linkedin.com/in/john-rodewald/", name = "LinkedIn"},
    {url = "https://github.com/john-rodewald/blog", name = "Source"},
]
zola = false
maintained_with_love = false
